// Language configuration — maps keys to Wikipedia subdomains
const LANGUAGES = {
    en:     { name: 'English',        domain: 'en.wikipedia.org' },
    simple: { name: 'Simple English', domain: 'simple.wikipedia.org' },
    es:     { name: 'Spanish',        domain: 'es.wikipedia.org' },
    de:     { name: 'German',         domain: 'de.wikipedia.org' },
    fr:     { name: 'French',         domain: 'fr.wikipedia.org' },
    ja:     { name: 'Japanese',       domain: 'ja.wikipedia.org' },
    pt:     { name: 'Portuguese',     domain: 'pt.wikipedia.org' }
};

const DEFAULT_LANGUAGE = 'en';

// UI translations — keyed by interface language
const TRANSLATIONS = {
    en: {
        tagline:          'Divination through encyclopedia',
        oneCard:          'One Card',
        threeCard:        'Three Card',
        celticCross:      'Celtic Cross',
        draw:             'Draw',
        settingsTitle:    'Settings',
        languageSection:  'Language',
        interfaceLanguage:'Interface:',
        articleLanguage:  'Articles:',
        articlesSection:  'Articles',
        disambigLabel:    'Include disambiguation pages',
        resetDefaults:    'Reset',
        save:             'Save',
        readArticle:      'Read Article',
        openInNewTab:     'Open in new tab',
        close:            'Close',
        footer:           "Because 78 cards wasn't enough.",
        settingsTooltip:  'Change position names and languages',
        errorMessage:     'The spirits of Wikipedia are currently unavailable.',
        tryAgain:         'Please try again.',
        settingsTab:      'Settings',
        spreadsTab:       'Spreads',
        shareTooltip:     'Copy shareable link',
        linkCopied:       'Link copied!',
        editSpread:       'Edit',
        deleteSpread:     'Delete',
        resetSpread:      'Reset',
        addPosition:      '+ Add Position',
        spreadName:       'Spread Name',
        positionName:     'Position',
        row:              'Row',
        col:              'Col',
        readingBtnTooltip: 'Set a reading topic',
        readingTitle:      'Your Reading Topic',
readingSave:       'Set Reading',
        readingClear:      'Clear',
        defaultPositions: {
            one:    'The Answer',
            three:  ['Past', 'Present', 'Future'],
            celtic: [
                'Present Situation', 'The Challenge', 'Crown (Conscious)',
                'Foundation (Unconscious)', 'Past', 'Future', 'Self',
                'Environment', 'Hopes & Fears', 'Outcome'
            ]
        }
    },
    simple: {
        tagline:          'Divination through encyclopedia',
        oneCard:          'One Card',
        threeCard:        'Three Card',
        celticCross:      'Celtic Cross',
        draw:             'Draw',
        settingsTitle:    'Settings',
        languageSection:  'Language',
        interfaceLanguage:'Interface:',
        articleLanguage:  'Articles:',
        articlesSection:  'Articles',
        disambigLabel:    'Include disambiguation pages',
        resetDefaults:    'Reset',
        save:             'Save',
        readArticle:      'Read Article',
        openInNewTab:     'Open in new tab',
        close:            'Close',
        footer:           "Because 78 cards wasn't enough.",
        settingsTooltip:  'Change position names and languages',
        errorMessage:     'Wikipedia is not working right now.',
        tryAgain:         'Please try again.',
        settingsTab:      'Settings',
        spreadsTab:       'Spreads',
        shareTooltip:     'Copy shareable link',
        linkCopied:       'Link copied!',
        editSpread:       'Edit',
        deleteSpread:     'Delete',
        resetSpread:      'Reset',
        addPosition:      '+ Add Position',
        spreadName:       'Spread Name',
        positionName:     'Position',
        row:              'Row',
        col:              'Col',
        readingBtnTooltip: 'Set a reading topic',
        readingTitle:      'Your Reading Topic',
        readingSave:       'Set Reading',
        readingClear:      'Clear',
        defaultPositions: {
            one:    'The Answer',
            three:  ['Past', 'Present', 'Future'],
            celtic: [
                'Now', 'Problem', 'Thoughts', 'Feelings', 'Past',
                'Future', 'You', 'Around You', 'Hopes & Fears', 'What Happens'
            ]
        }
    },
    es: {
        tagline:          'Adivinación a través del esoterismo',
        oneCard:          'Una Carta',
        threeCard:        'Tres Cartas',
        celticCross:      'Cruz Céltica',
        draw:             'Sacar',
        settingsTitle:    'Configuración',
        languageSection:  'Idioma',
        interfaceLanguage:'Interfaz:',
        articleLanguage:  'Artículos:',
        articlesSection:  'Artículos',
        disambigLabel:    'Incluir páginas de desambiguación',
        resetDefaults:    'Restablecer',
        save:             'Guardar',
        readArticle:      'Leer Artículo',
        openInNewTab:     'Abrir en nueva pestaña',
        close:            'Cerrar',
        footer:           'Porque 78 cartas no eran suficientes.',
        settingsTooltip:  'Cambiar nombres de posiciones e idiomas',
        errorMessage:     'Los espíritus de Wikipedia no están disponibles.',
        tryAgain:         'Por favor, inténtalo de nuevo.',
        settingsTab:      'Ajustes',
        spreadsTab:       'Tiradas',
        shareTooltip:     'Copiar enlace',
        linkCopied:       '¡Enlace copiado!',
        editSpread:       'Editar',
        deleteSpread:     'Eliminar',
        resetSpread:      'Restablecer',
        addPosition:      '+ Agregar posición',
        spreadName:       'Nombre de la tirada',
        positionName:     'Posición',
        row:              'Fila',
        col:              'Col',
        readingBtnTooltip: 'Establecer un tema de lectura',
        readingTitle:      'Tu tema de lectura',
        readingSave:       'Guardar tema',
        readingClear:      'Borrar',
        defaultPositions: {
            one:    'La Respuesta',
            three:  ['Pasado', 'Presente', 'Futuro'],
            celtic: [
                'Situación Actual', 'El Desafío', 'Corona (Consciente)',
                'Base (Inconsciente)', 'Pasado', 'Futuro', 'Yo',
                'Entorno', 'Esperanzas y Miedos', 'Resultado'
            ]
        }
    },
    de: {
        tagline:          'Wahrsagung durch Esoterik',
        oneCard:          'Eine Karte',
        threeCard:        'Drei Karten',
        celticCross:      'Keltisches Kreuz',
        draw:             'Ziehen',
        settingsTitle:    'Einstellungen',
        languageSection:  'Sprache',
        interfaceLanguage:'Oberfläche:',
        articleLanguage:  'Artikel:',
        articlesSection:  'Artikel',
        disambigLabel:    'Begriffsklärungsseiten einschließen',
        resetDefaults:    'Zurücksetzen',
        save:             'Speichern',
        readArticle:      'Artikel lesen',
        openInNewTab:     'In neuem Tab öffnen',
        close:            'Schließen',
        footer:           'Weil 78 Karten nicht genug waren.',
        settingsTooltip:  'Positionsnamen und Sprachen ändern',
        errorMessage:     'Die Geister von Wikipedia sind derzeit nicht verfügbar.',
        tryAgain:         'Bitte versuche es erneut.',
        settingsTab:      'Einstellungen',
        spreadsTab:       'Legungen',
        shareTooltip:     'Link kopieren',
        linkCopied:       'Link kopiert!',
        editSpread:       'Bearbeiten',
        deleteSpread:     'Löschen',
        resetSpread:      'Zurücksetzen',
        addPosition:      '+ Position hinzufügen',
        spreadName:       'Name der Legung',
        positionName:     'Position',
        row:              'Zeile',
        col:              'Spalte',
        readingBtnTooltip: 'Lesethema festlegen',
        readingTitle:      'Dein Lesethema',
        readingSave:       'Thema speichern',
        readingClear:      'Leeren',
        defaultPositions: {
            one:    'Die Antwort',
            three:  ['Vergangenheit', 'Gegenwart', 'Zukunft'],
            celtic: [
                'Aktuelle Situation', 'Die Herausforderung', 'Krone (Bewusst)',
                'Fundament (Unbewusst)', 'Vergangenheit', 'Zukunft', 'Selbst',
                'Umgebung', 'Hoffnungen & Ängste', 'Ergebnis'
            ]
        }
    },
    fr: {
        tagline:          'Divination par l\'ésotérisme',
        oneCard:          'Une Carte',
        threeCard:        'Trois Cartes',
        celticCross:      'Croix Celtique',
        draw:             'Tirer',
        settingsTitle:    'Paramètres',
        languageSection:  'Langue',
        interfaceLanguage:'Interface :',
        articleLanguage:  'Articles :',
        articlesSection:  'Articles',
        disambigLabel:    'Inclure les pages de désambiguïsation',
        resetDefaults:    'Réinitialiser',
        save:             'Enregistrer',
        readArticle:      'Lire l\'Article',
        openInNewTab:     'Ouvrir dans un nouvel onglet',
        close:            'Fermer',
        footer:           "Parce que 78 cartes n'étaient pas suffisantes.",
        settingsTooltip:  'Changer les noms de positions et les langues',
        errorMessage:     'Les esprits de Wikipédia sont actuellement indisponibles.',
        tryAgain:         'Veuillez réessayer.',
        settingsTab:      'Paramètres',
        spreadsTab:       'Tirages',
        shareTooltip:     'Copier le lien',
        linkCopied:       'Lien copié !',
        editSpread:       'Modifier',
        deleteSpread:     'Supprimer',
        resetSpread:      'Réinitialiser',
        addPosition:      '+ Ajouter une position',
        spreadName:       'Nom du tirage',
        positionName:     'Position',
        row:              'Ligne',
        col:              'Col',
        readingBtnTooltip: 'Définir un sujet de lecture',
        readingTitle:      'Votre sujet de lecture',
        readingSave:       'Définir le sujet',
        readingClear:      'Effacer',
        defaultPositions: {
            one:    'La Réponse',
            three:  ['Passé', 'Présent', 'Futur'],
            celtic: [
                'Situation Actuelle', 'Le Défi', 'Couronne (Conscient)',
                'Fondation (Inconscient)', 'Passé', 'Futur', 'Soi',
                'Environnement', 'Espoirs & Peurs', 'Résultat'
            ]
        }
    },
    ja: {
        tagline:          '神秘を通じた占い',
        oneCard:          '1枚のカード',
        threeCard:        '3枚のカード',
        celticCross:      'ケルト十字',
        draw:             '引く',
        settingsTitle:    '設定',
        languageSection:  '言語',
        interfaceLanguage:'インターフェース:',
        articleLanguage:  '記事:',
        articlesSection:  '記事',
        disambigLabel:    '曖昧さ回避ページを含める',
        resetDefaults:    'リセット',
        save:             '保存',
        readArticle:      '記事を読む',
        openInNewTab:     '新しいタブで開く',
        close:            '閉じる',
        footer:           '78枚のカードでは足りなかったから。',
        settingsTooltip:  'ポジション名と言語を変更',
        errorMessage:     'Wikipediaの精霊は現在利用できません。',
        tryAgain:         'もう一度お試しください。',
        settingsTab:      '設定',
        spreadsTab:       'スプレッド',
        shareTooltip:     'リンクをコピー',
        linkCopied:       'リンクをコピーしました！',
        editSpread:       '編集',
        deleteSpread:     '削除',
        resetSpread:      'リセット',
        addPosition:      '+ 位置を追加',
        spreadName:       'スプレッド名',
        positionName:     'ポジション',
        row:              '行',
        col:              '列',
        readingBtnTooltip: '読みのテーマを設定',
        readingTitle:      '読みのテーマ',
        readingSave:       'テーマを設定',
        readingClear:      'クリア',
        defaultPositions: {
            one:    '答え',
            three:  ['過去', '現在', '未来'],
            celtic: [
                '現在の状況', '課題', '王冠（意識）', '基礎（無意識）',
                '過去', '未来', '自己', '環境', '希望と恐れ', '結果'
            ]
        }
    },
    pt: {
        tagline:          'Adivinhação através do esoterismo',
        oneCard:          'Uma Carta',
        threeCard:        'Três Cartas',
        celticCross:      'Cruz Celta',
        draw:             'Puxar',
        settingsTitle:    'Configurações',
        languageSection:  'Idioma',
        interfaceLanguage:'Interface:',
        articleLanguage:  'Artigos:',
        articlesSection:  'Artigos',
        disambigLabel:    'Incluir páginas de desambiguação',
        resetDefaults:    'Redefinir',
        save:             'Salvar',
        readArticle:      'Ler Artigo',
        openInNewTab:     'Abrir em nova aba',
        close:            'Fechar',
        footer:           'Porque 78 cartas não eram suficientes.',
        settingsTooltip:  'Alterar nomes de posições e idiomas',
        errorMessage:     'Os espíritos da Wikipédia estão atualmente indisponíveis.',
        tryAgain:         'Por favor, tente novamente.',
        settingsTab:      'Configurações',
        spreadsTab:       'Tiragens',
        shareTooltip:     'Copiar link',
        linkCopied:       'Link copiado!',
        editSpread:       'Editar',
        deleteSpread:     'Excluir',
        resetSpread:      'Redefinir',
        addPosition:      '+ Adicionar posição',
        spreadName:       'Nome da tiragem',
        positionName:     'Posição',
        row:              'Linha',
        col:              'Col',
        readingBtnTooltip: 'Definir um tema de leitura',
        readingTitle:      'Seu tema de leitura',
        readingSave:       'Definir tema',
        readingClear:      'Limpar',
        defaultPositions: {
            one:    'A Resposta',
            three:  ['Passado', 'Presente', 'Futuro'],
            celtic: [
                'Situação Atual', 'O Desafio', 'Coroa (Consciente)',
                'Fundação (Inconsciente)', 'Passado', 'Futuro', 'Eu',
                'Ambiente', 'Esperanças e Medos', 'Resultado'
            ]
        }
    }
};
